name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (Latest)
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          push: true
          tags: digglepress/optimise_django_orm:latest

      - name: Build and push (Github SHA)
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          push: true
          tags: digglepress/optimise_django_orm:${GITHUB_SHA::5}
